# -*- coding: utf-8 -*-
"""data_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IncQO2gn9jyR5xoo-Pur1xigeANtaTBF
"""

import os
os.environ["NUMBA_DISABLE_JIT"] = "1"
os.environ["NUMBA_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
print("Pinned threads + disabled numba JIT")

from prompt_progenitor import Prompt

import numpy as np
from pathlib import Path

# from gemma.ejecta.physics.jet.prompt import Prompt

def interp_logt(t_new, t, y, left=0.0, right=0.0):
    # assumes t increasing
    return np.interp(t_new, t, y, left=left, right=right)

def sample_params(rng):
    m1 = rng.uniform(1.0, 2.5)
    m2 = rng.uniform(1.0, 2.5)
    if m2 > m1:
        m1, m2 = m2, m1

    return {
        "theta_los": rng.uniform(0.0, 90.0),
        "mass_1": m1,
        "mass_2": m2,
        "lambda_2": rng.uniform(100, (2000.0)),  # optional
        # "luminosity_distance": 10**rng.uniform(1.0, np.log10(500.0)),
    }

def featurize(p):
    # Convert dict -> feature vector in a consistent order
    # (Use the same ordering everywhere.)
    theta_los = p["theta_los"] / 90.0
    m1 = p["mass_1"]
    m2 = p["mass_2"]
    lam = np.log10(p["lambda_2"] + 1.0)
    return np.array([theta_los, m1, m2, lam], dtype=np.float32)

def main():
    rng = np.random.default_rng(29)

    # Fixed emulator time grid (choose something covering your regime)
    # You can also clip to what Prompt produces, but fixed is easiest.
    t_grid = np.logspace(-3, 6, 1000).astype(np.float32)  # 1s .. 1e6s

    # Wrapper
    prompt = Prompt(
        components=("jet",),
        sample_gw_parameters=False,
        gw_param_mode="mass",
        j_struct="tophat",
        use_disk_mass_mapping=True,
        output="luminosity",  # or "flux"
        default_theta_los_deg=0.0,
        # if flux:
        # default_distance_mpc=40.0,
        # sample_distance=False,
    )

    N = 2  # start small; scale later
    X = np.zeros((N, 4), dtype=np.float32)
    Y = np.zeros((N, t_grid.size), dtype=np.float64)
    Z = np.zeros((N, t_grid.size), dtype=np.float64)

    # floor for log transform (pick something tiny in your chosen units)
    y_floor = 1e-40

    n_ok = 0
    i = 0
    while n_ok < N:
        i += 1
        p = sample_params(rng)

        try:
            prompt.update_model(p, dry_run=False, verbose=False)
            if (not np.isfinite(prompt.mdisk)) or (prompt.mdisk <= 0.0):
                continue

            t_model = np.asarray(prompt.t, dtype=np.float32)
            y_model = np.asarray(prompt.total_X, dtype=np.float64)
            z_model = np.asarray(prompt.total_gamma, dtype=np.float64)

            # interpolate onto fixed grid
            y_interp = interp_logt(t_grid, t_model, y_model, left=0.0, right=0.0)
            z_interp = interp_logt(t_grid, t_model, z_model, left=0.0, right=0.0)

            # log-transform target
            y_target = np.log10(y_interp + y_floor).astype(np.float64)
            z_target = np.log10(z_interp + y_floor).astype(np.float64)

            X[n_ok] = featurize(p)
            Y[n_ok] = y_target
            Z[n_ok] = z_target
            n_ok += 1

            if n_ok % 50 == 0:
                print(f"Generated {n_ok}/{N} ok (attempts={i})")

        except Exception as e:
            print(f"Rejected on attempt {i}: {type(e).__name__}: {e}")
            continue

    out = Path("prompt_bns_dataset_2.npz")
    np.savez(out, X=X, Y=Y, Z=Z, t_grid=t_grid, y_floor=y_floor)
    print("Saved:", out.resolve())

if __name__ == "__main__":
    main()

